repository:
  name: cli-messages
  description: status messaging for output of CLI applications
  homepage: https://npm.im/@travi/cli-messages
  private: false
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
  - name: bug
    color: ee0701
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb
  - name: help wanted
    color: 128A0C
  - name: invalid
    color: e6e6e6
  - name: question
    color: cc317c
  - name: wontfix
    color: ffffff
  - name: breaking change
    color: e0fc28
  - name: greenkeeper
    color: 00c775
branches:
  - name: master
    protection: null
collaborators:
  - username: travi-bot
    permission: push
rulesets:
  - name: prevent destruction of the default branch
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []
    rules:
      - type: deletion
      - type: non_fast_forward
  - name: verification must pass
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []
    rules:
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: false
          required_status_checks:
            - context: workflow-result
              integration_id: 15368
    bypass_actors:
      - actor_id: 5
        actor_type: RepositoryRole
        bypass_mode: always
